# Generated by Django 3.2.5 on 2022-07-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='likes',
            new_name='sub_count',
        ),
    ]
