# Generated by Django 3.2.5 on 2022-07-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_rename_likes_problems_sub_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='sub_count',
        ),
    ]
