# Generated by Django 3.2.5 on 2022-07-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_remove_problems_sub_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problems',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problems',
            name='statement',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutions',
            name='verdict',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcases',
            name='input',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcases',
            name='output',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
