# Generated by Django 4.0.6 on 2022-07-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_auto_20220704_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='submitted_code',
            field=models.TextField(default='code'),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='output',
            field=models.TextField(),
        ),
    ]
