# Generated by Django 4.0.6 on 2022-07-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0006_alter_solutions_submitted_code_alter_testcases_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='statement',
            field=models.TextField(),
        ),
    ]
